Setup PG, knex migrations, express and make health check route.
Skoryts/fitOrDead pull request #8
Opened 2018-09-20 11:22 UTC by Skoryts

2018-09-20 11:30 UTC, belevtsev requested changes

2018-09-20 11:30 UTC, belevtsev commented on api/app.js
> +require('./db');
You should create a db class and use it everywhere.
Please read how to use pool correctly.

2018-09-20 11:30 UTC, belevtsev commented on api/app.js
> +const port = 3000;
please use env file

2018-09-20 11:30 UTC, belevtsev commented on api/db.js
> +const connectionString = 'postgres://wqhrrievdwrbco:4bc4d6ecd015e4a72356e19e9ddaebc8c0c343188716a94914489fd2af1be00c@ec2-54-217-236-201.eu-west-1.compute.amazonaws.com:5432/dfocldlmhfo197';
please use env file

2018-09-20 11:30 UTC, belevtsev commented on api/db.js
> +(async function(){
is it useful for you? If yes, please tell me why?

2018-09-20 11:30 UTC, belevtsev commented on api/knexfile.js
> +  production: {
please remove

2018-09-20 11:30 UTC, belevtsev commented on api/knexfile.js
> +    connection: {
please use env file.

2018-09-20 11:30 UTC, belevtsev commented on api/migrations/20180920142003_test.js
> +exports.up = function(knex, Promise) {
Please create something here.

2018-09-27 08:24 UTC, belevtsev requested changes

2018-09-27 08:24 UTC, belevtsev commented on .eslintrc.yml
> -  - airbnb
https://www.npmjs.com/package/eslint-config-airbnb-base

2018-09-27 08:24 UTC, belevtsev commented on .eslintrc.yml
> -  linebreak-style:
linebreak-style should be present.

2018-09-27 08:24 UTC, belevtsev commented on api/config.js
> +require('dotenv').config({path: '../.env'});
please add `{ silent: true }`.

2018-09-27 08:24 UTC, belevtsev commented on api/config.js
> +  db: process.env.DB_CONNECTION
`db ` -> `db_uri`

2018-09-27 08:24 UTC, belevtsev commented on api/db.js
> +    return new Promise((resolve, reject) => {
async await

2018-09-27 08:24 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.increments('id').unsigned().primary();
what about uuid?

2018-09-27 08:24 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('createdAt').notNull();
default value?

2018-09-27 08:24 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('updatedAt').nullable();
default value?

2018-09-27 08:24 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('deletedAt').nullable();
default value?

2018-09-27 08:24 UTC, belevtsev commented on .env.example
> +DB_CONNECTION=
`DB_CONNECTION ` -> `DB_URI`

2018-09-27 16:09 UTC, Skoryts commented on .eslintrc.yml
> -  - airbnb
I have installed, but now I need to left trailing comma! I hate trailing commas.

2018-09-27 17:36 UTC, Skoryts commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('updatedAt').nullable();
Why we need default value? This column we need to fill, when row has been updated.

2018-09-27 17:37 UTC, Skoryts commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('deletedAt').nullable();
Why we need default value? This column we need to fill, when row will be deleted.

2018-10-01 06:59 UTC, belevtsev requested changes

2018-10-01 06:59 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('updatedAt').nullable();
You should have an experience to write triggers.

2018-10-01 06:59 UTC, belevtsev commented on api/migrations/20180926201759_create_users.js
> +    t.dateTime('deletedAt').nullable();
You should have an experience to write triggers.

2018-10-01 06:59 UTC, belevtsev commented on .eslintrc.yml
> -  - airbnb
let it be.

2018-10-01 19:09 UTC, belevtsev approved these changes

2018-10-02 08:15 UTC, merged